import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-24">
          <h1 className="text-center text-3xl font-bold mb-5">TODO APP</h1>
          <div>{children}</div>
          <Link className="w-fit mx-auto block mt-5" href="/">
            TOPへ戻る
          </Link>
        </div>
      </body>
    </html>
  );
}
